name: RAMdevelopment
favicon: null
layout_spectrum: 0.7365691736340523
typography_spectrum: 0.21249047736637294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.827523946762085
  lightness: 0.2344119579065591
  saturation: 0.5227657158393413
  rhythmicContrast: 0.2917223460972309
purpose: []
